### ISSUE TITLE
Error: AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by SvenMeyer** [alchemyplatform/create-web3-dapp#110]
**Describe the bug**
Tried to create a NFT boilerplate project 

**To Reproduce**

```
$ npx create-web3-dapp@latest


Welcome to the create-web3-dapp wizard 🔮

⏳ Checking for new updates...
✔ Project name … create-web3-dapp
✔ Choose how to start › NFT Explorer
✔ Choose your chain › Ethereum
✔ [Optional] Choose your blockchain development environment: › Hardhat
✔ Do you want to create a smart contract? › Yes
✔ What kind of smart contract do you want to create? › ERC721
✔ Name for you contract … NFT1
✔ Symbol for your contract … NFT1
✔ Smart contract features to implement › Auto Increment, Enumerable, Roles
✔ Are you done selecting contract features? … no / yes
✔ Do you already have an Alchemy account? … no / yes
✔ Insert your Alchemy API Key (Copy from https://auth.alchemy.com/?a=create-web3-dapp): … Rc_XipaZj2ee4tOOlPG3st352hnYQBV7
✔ Help us improve create-web3-dapp with anonymous crash & basic usage data? … no / yes
Error: AxiosError: Request failed with status code 403
    at settle (file:///home/sum/.npm/_npx/373f6439c04079cf/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///home/sum/.npm/_npx/373f6439c04079cf/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Axios.request (file:///home/sum/.npm/_npx/373f6439c04079cf/node_modules/axios/lib/core/Axios.js:44:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },

...
```

I provided the API key for a project with the same name like I used here.
Tried zkEVM and Ethereum chain - same result.

**Desktop (please complete the following information):**
 - OS: Arch Linux / Manjaro

**Comment by Haavi97** [comment]
I have the same error, but I think is related to providing crash & basic usage data, so no big deal. I have the impresion they have discontinued the maintenance of this repo.

**Comment by Dan-Nolan** [comment]
Thank you for opening up this issue! 

We just put out a new release #124 which will fix this issue and make use of [Scaffold-Alchemy](https://github.com/alchemyplatform/scaffold-alchemy). Check it out when you have the change 😄
