### ISSUE TITLE
Error with NFT Explorer template

### ISSUE THREAD

**Issue by SvenMeyer** [alchemyplatform/create-web3-dapp#92]
When using `create-web3-test1` to create the NFT Template I ran into two issues ...

```
$ npx create-web3-dapp@latest
...
✔ Project name … create-web3-test1
✔ Choose how to start: › Create pre-built template
✔ Select a template › NFT Explorer
...
```

```
$ cd create-web3-test1 && npm run dev

> create-web3-test1@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/sum/DEV/ETH/0x-Exchange/create-web3-test1/.env.local
error - ./components/navigation/navbar.jsx:1:0
Module not found: Can't resolve '@rainbow-me/rainbowkit'
> 1 | import { ConnectButton } from "@rainbow-me/rainbowkit";
  2 | import styles from "../../styles/Navbar.module.css";
  3 | export default function Navbar() {
  4 | 	return (

Import trace for requested module:
./layout/mainLayout.jsx
./pages/_app.js

https://nextjs.org/docs/messages/module-not-found
```

fixed that with `npm i @rainbow-me/rainbowkit`

Started the App and got this error 

```
$ npm run dev

> create-web3-test1@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/sum/DEV/ETH/0x-Exchange/create-web3-test1/.env.local
event - compiled client and server successfully in 6.2s (1373 modules)
wait  - compiling...
event - compiled client and server successfully in 476 ms (1373 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 570 ms (1384 modules)
wait  - compiling /_error (client and server)...
error - pages/_app.js (39:33) @ eval
error - TypeError: (0 , wagmi__WEBPACK_IMPORTED_MODULE_4__.createClient) is not a function
    at eval (webpack-internal:///./pages/_app.js:50:72) {
  page: '/'
}
  37 | });
  38 | 
> 39 | const wagmiClient = createClient({
     |                                 ^
  40 | 	autoConnect: true,
  41 | 	connectors,
  42 | 	provider,
event - compiled client and server successfully in 305 ms (1385 modules)
TypeError: (0 , wagmi__WEBPACK_IMPORTED_MODULE_4__.createClient) is not a function
    at eval (webpack-internal:///./pages/_app.js:50:72)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: (0 , wagmi__WEBPACK_IMPORTED_MODULE_4__.createClient) is not a function
    at eval (webpack-internal:///./pages/_app.js:50:72)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Dan-Nolan** [comment]
Thank you for opening up this issue! 

We just put out a new release #124 which will fix this issue and make use of [Scaffold-Alchemy](https://github.com/alchemyplatform/scaffold-alchemy). Check it out when you have the change 😄
